export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_REQUEST = 'FETCH_PLANETS_REQUEST';
export const FETCH_PLANETS_FAILURE = 'FETCH_PLANETS_FAILURE';